version: 2
jobs:
  deploy_prod:
    working_directory: ~/trackit2-client
    docker:
      - image: msolution/trackit2-builder-ui
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Installing NPM dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          environment:
            CI: 'false'
          name: Building
          command: npm run build
      - deploy:
          name: Deploying
          command: aws s3 sync --delete build/ $S3_DOCUMENTATION_DESTINATION
workflows:
  version: 2
  deploy:
    jobs:
      - deploy_prod
